<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class courses extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('courses')->insert(
          [  [
                'course_code' => 'CSE 100',
                'course_name' => 'Software Development I',
                'department' => 'CSE',
                'credit' => 0.75,
            ],
            [
            'course_code' => 'ACT 201',
            'course_name' => 'Accounting Fundamentals',
            'department' => 'CSE',
            'credit' => 2,
            ],
        
           [ 'course_code' => 'CSE 101',
            'course_name' => 'Computer and Programming Concepts',
            'department' => 'CSE',
            'credit' => 3,
            ],
            [
                'course_code' => 'CSE 102',
                'course_name' => 'Computer and Programming Concepts Lab',
                'department' => 'CSE',
                'credit' => 1.5,
            ],
       
            [
                    'course_code' => 'CSE 103',
                    'course_name' => 'Discrete Mathematics',
                    'department' => 'CSE',
                    'credit' => 	3,
            ],
            [
                        'course_code' => 'CSE 111',
                        'course_name' => 'Structured Programming Language',
                        'department' => 'CSE',
                        'credit' => 	3,
             ],
             [
                            'course_code' => 'CSE 112',
                            'course_name' => 'Structured Programming Language Lab',
                            'department' => 'CSE',
                            'credit' => 	1.5,
            ],
                            [
                                'course_code' => 'CSE 121',
                                'course_name' => 'Object Oriented Programming Language',
                                'department' => 'CSE',
                                'credit' => 	3,
                                ],
                                [
                                    'course_code' => 'CSE 122',
                                    'course_name' => 'Object Oriented Programming Language Lab',
                                    'department' => 'CSE',
                                    'credit' => 	1.5,
                                    ],
                                    [
                                        'course_code' => 'CSE 200',
                                        'course_name' => 'Software Development II',
                                        'department' => 'CSE',
                                        'credit' =>0.75,
                                        ],
                                        [
                                            'course_code' => 'CSE 205',
                                            'course_name' => 'Digital Logic Design',
                                            'department' => 'CSE',
                                            'credit' => 3,
                                            ],
                                            [
                                                'course_code' => 'CSE 206',
                                                'course_name' => 'Digital Logic Design Lab',
                                                'department' => 'CSE',
                                                'credit' => 1.5,
                                                ],
                                                [
                                                    'course_code' => 'CSE 207',
                                                    'course_name' => 'Database Systems',
                                                    'department' => 'CSE',
                                                    'credit' => 	3,
                                                    ],
                                                    [
                                                        'course_code' => 'CSE 208',
                                                        'course_name' => 'Database Systems Lab',
                                                        'department' => 'CSE',
                                                        'credit' => 1.5,
                                                        ],
                                                        [
                                                            'course_code' => 'CSE 209',
                                                            'course_name' => 'Data Communication',
                                                            'department' => 'CSE',
                                                            'credit' => 	3,
                                                            ],
                                                            [
                                                                'course_code' => 'CSE 213',
                                                                'course_name' => 'Theory of Computing & Automata Theory',
                                                                'department' => 'CSE',
                                                                'credit' => 	3,
                                                                ],
                                                                [
                                                                    'course_code' => 'CSE 215',
                                                                    'course_name' => 'Computer Architecture',
                                                                    'department' => 'CSE',
                                                                    'credit' => 	3,
                                                                    ],
                                                                    [
                                                                        'course_code' => 'CSE 223',
                                                                        'course_name' => 'Numerical Analysis',
                                                                        'department' => 'CSE',
                                                                        'credit' => 	3,
                                                                        ],
                                                                        [
                                                                            'course_code' => 'CSE 224',
                                                                            'course_name' => 'Numerical Analysis Lab',
                                                                            'department' => 'CSE',
                                                                            'credit' => 	0.75,
                                                                            ],
                                                                            [
                                                                                'course_code' => 'CSE 231',
                                                                                'course_name' => 'Data Structures',
                                                                                'department' => 'CSE',
                                                                                'credit' => 	3,
                                                                                ],
                                                                                [
                                                                                    'course_code' => 'CSE 232',
                                                                                    'course_name' => 'Data Structures Lab',
                                                                                    'department' => 'CSE',
                                                                                    'credit' => 		1.5,
                                                                                    ],
                                                                                    [
                                                                                        'course_code' => 'CSE 241',
                                                                                        'course_name' => 'Algorithms',
                                                                                        'department' => 'CSE',
                                                                                        'credit' => 	3,
                                                                                        ],
                         [
                              'course_code' => 'CSE 242',
                              'course_name' => 'Algorithms Lab',
                               'department' => 'CSE',
                           'credit' =>	1.5,
                         ],
                         [
                            'course_code' => 'CSE 300',
                            'course_name' => 'Software Development III',
                             'department' => 'CSE',
                         'credit' =>	0.75,
                       ],
                       [
                        'course_code' => 'CSE 309',
                        'course_name' => 'Operating Systems',
                         'department' => 'CSE',
                     'credit' =>	3,
                   ],
                   [
                    'course_code' => 'CSE 310',
                    'course_name' => 'Operating Systems Lab',
                     'department' => 'CSE',
                     'credit' =>	1.5,
               ],
               [
                'course_code' => 'CSE 313',
                'course_name' => 'Mathematical Analysis for Computer Science',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 315',
                'course_name' => 'Microprocessor and Interfacing',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 316',
                'course_name' => 'Microprocessor and Interfacing Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 317',
                'course_name' => 'System Analysis and Design',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 318',
                'course_name' => 'System Analysis and Design Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 319',
                'course_name' => 'Computer Network',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 320',
                'course_name' => 'Computer Network Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 323',
                'course_name' => 'Compiler Design',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 324',
                'course_name' => 'Compiler Design Lab',
                 'department' => 'CSE',
                 'credit' =>	0.75,
              ],
              [
                'course_code' => 'CSE 327',
                'course_name' => 'Software Engineering',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 328',
                'course_name' => 'Software Engineering Lab',
                 'department' => 'CSE',
                 'credit' =>	0.75,
              ],
              [
                'course_code' => 'CSE 331',
                'course_name' => 'Advanced Programming',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 332',
                'course_name' => 'Advanced Programming Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 341',
                'course_name' => 'Computer Graphics',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 342',
                'course_name' => 'Computer Graphics Lab',
                 'department' => 'CSE',
                 'credit' =>	0.75,
              ],
              [
                'course_code' => 'CSE 351',
                'course_name' => 'Artificial Intelligence and Expert System',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 352',
                'course_name' => 'Artificial Intelligence and Expert System Lab',
                 'department' => 'CSE',
                 'credit' =>		1.5,
              ],
              [
                'course_code' => 'CSE 400',
                'course_name' => 'Software Development IV',
                 'department' => 'CSE',
                 'credit' =>	0.75,
              ],
              [
                'course_code' => 'CSE 407',
                'course_name' => 'Project Management and Professional Ethics',
                 'department' => 'CSE',
                 'credit' =>	2,
              ],
              [
                'course_code' => 'CSE 413',
                'course_name' => 'Cyber Security and Digital Forensic',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 414',
                'course_name' => 'Cyber Security and Digital Forensic Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 417',
                'course_name' => 'Distributed Database Management Systems',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 418',
                'course_name' => 'Distributed Database Management Systems Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 425',
                'course_name' => 'Microcontroller and Embedded Systems',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 426',
                'course_name' => 'Microcontroller and Embedded Systems Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 465',
                'course_name' => 'Machine Learning',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 477',
                'course_name' => 'Neural Network and Fuzzy Systems',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 478',
                'course_name' => 'Neural Network and Fuzzy Systems Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'ECO 101',
                'course_name' => 'Principles of Economics',
                 'department' => 'CSE',
                 'credit' =>	2,
              ],
              [
                'course_code' => 'EEE 101',
                'course_name' => 'Electrical Technology',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'EEE 102',
                'course_name' => 'Electrical Technology Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'EEE 211',
                'course_name' => 'Electronic Devices and Circuits',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'EEE 212',
                'course_name' => 'Electronic Devices and Circuits Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'ENG 101',
                'course_name' => 'English Language-I',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'ENG 111',
                'course_name' => 'English Language-II',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'MAT 101',
                'course_name' => 'Differential and Integral Calculus',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'MAT 111',
                'course_name' => 'Co-Ordinate Geometry and Vector Calculus',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'MAT 121',
                'course_name' => 'Linear Algebras and Differential Equations',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'MAT 231',
                'course_name' => 'Complex Variable and Fourier Analysis',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'PHY 101',
                'course_name' => 'Physics',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'STA 231',
                'course_name' => 'Statistics',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 105',
                'course_name' => 'Object Oriented Programming Language',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 106',
                'course_name' => 'Object Oriented Programming Language',
                 'department' => 'CSE',
                 'credit' =>		1.5,
              ],
              [
                'course_code' => 'CSE 107',
                'course_name' => 'Electrical Technology',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 108',
                'course_name' => 'Electrical Technology Lab',
                 'department' => 'CSE',
                 'credit' =>		1.5,
              ],
              [
                'course_code' => 'CSE 411',
                'course_name' => 'Digital Electronics and Pulse Technique',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 412',
                'course_name' => 'Digital Electronics and Pulse Technique Lab',
                 'department' => 'CSE',
                 'credit' =>		1.5,
              ],
              [
                'course_code' => 'CSE 431',
                'course_name' => 'Communication Engineering',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 433',
                'course_name' => 'Fiber Optics Communication',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 435',
                'course_name' => 'Network Security',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 437',
                'course_name' => 'Digital Signal Processing',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 438',
                'course_name' => 'Digital Signal Processing Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 439',
                'course_name' => 'Wireless Networking',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 440',
                'course_name' => 'Wireless Networking Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 441',
                'course_name' => 'Switching and Routing',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 442',
                'course_name' => 'Switching and Routing Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 443',
                'course_name' => 'Delay Tollerant Network',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 444',
                'course_name' => 'Delay Tollerant Network Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 445',
                'course_name' => 'Introduction to Cryptography',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 446',
                'course_name' => 'Introduction to Cryptography Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 447',
                'course_name' => 'Mobile Communication',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 448',
                'course_name' => 'Mobile Communication Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 449',
                'course_name' => 'Network Administration',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 450',
                'course_name' => 'Network Administration Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 451',
                'course_name' => 'Software Project Management',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 453',
                'course_name' => 'Software Testing & Quality Assurance',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 455',
                'course_name' => 'Software Security & Authentication',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 457',
                'course_name' => 'Web Database Programming',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 458',
                'course_name' => 'Web Database Programming Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 459',
                'course_name' => 'Visual Programming',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 460',
                'course_name' => 'Visual Programming Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 461',
                'course_name' => 'Software Architecture',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 462',
                'course_name' => 'Software Architecture Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 463',
                'course_name' => 'Software Design Pattern',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 464',
                'course_name' => 'Software Design Pattern Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 467',
                'course_name' => 'Pattern Recognition',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 469',
                'course_name' => 'Basic Graph Theory',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 471',
                'course_name' => 'Computational Geometry',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 473',
                'course_name' => 'Simulation and Modeling',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 474',
                'course_name' => 'Simulation and Modeling Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 475',
                'course_name' => 'Data Mining',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 476',
                'course_name' => 'Data Mining Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 479',
                'course_name' => 'VLSI Design',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 480',
                'course_name' => 'VLSI Design Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 481',
                'course_name' => 'Decision Support System',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 482',
                'course_name' => 'Decision Support System Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 483',
                'course_name' => 'Knowledge Engineering',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 484',
                'course_name' => 'Knowledge Engineering Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 485',
                'course_name' => 'PParallel Processing',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 487',
                'course_name' => 'Robotics and Computer Vision',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 489',
                'course_name' => 'Fault Tolerant System',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 491',
                'course_name' => 'Interfacing & Peripherals',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 492',
                'course_name' => 'Interfacing & Peripherals Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 493',
                'course_name' => 'Digital System Design',
                 'department' => 'CSE',
                 'credit' =>	3,
              ],
              [
                'course_code' => 'CSE 494',
                'course_name' => 'Degital System Design Lab',
                 'department' => 'CSE',
                 'credit' =>	1.5,
              ],
              [
                'course_code' => 'CSE 499',
                'course_name' => 'Capstone Project',
                 'department' => 'CSE',
                 'credit' =>	4,
              ]
            ]
     
    );
    }
}
